export const ACTIONS = {
  ADD: 'ADD',
  REMOVE: 'REMOVE',
  EDIT: 'EDIT',
  CLEAR_ALL: 'CLEAR_ALL',
  SET_LOADING: 'SET_LOADING',
  UNSET_LOADING: 'UNSET_LOADING',
  SET_THEME_FROM_LOCALSTORAGE: 'SET_THEME_FROM_LOCALSTORAGE',
  SET_DARK_THEME: 'SET_DARK_THEME',
  SET_LIGHT_THEME: 'SET_LIGHT_THEME',
  SET_TODO_LIST_FROM_DB: 'SET_TODO_LIST_FROM_DB',
  DONE: 'DONE',
  NOT_DONE: 'NOT_DONE',
};
